### ISSUE TITLE
better error when cookies are disabled

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-saml-sp#3]
![signal-2020-04-17-115358](https://user-images.githubusercontent.com/616885/79557370-bc464300-80a2-11ea-85f0-2aff15267dac.png)

**Comment by fkooman** [comment]
I think this is slightly different now in upcoming 0.4 as `auth_options` session is not there anymore... it will probably result in another error!

TODO: test without cookies to see what happens.

**Comment by fkooman** [comment]
```
Error
500 - Internal Server Error
Error Message
"RelayState" not found in session data
```

**Comment by fkooman** [comment]
we could add a method to Session class and ask if it is a "new" session. i.e. no valid session cookie was received from the browser. In that case during ACS we should give a better error: e.g. "no existing session, cookies disabled?"

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/100895780-d90a7c00-34b5-11eb-8a75-049942e1b058.png)

**Comment by TanguiC** [comment]
ok as a normal user I'd say most of the information is irrelevant for me. What shall I do? Help? 400 - ah, thanks? I was worried I did a 700! I don't need to be exposed to your own codes

**Comment by TanguiC** [comment]
what about suggestions: "Hey something went wrong! Can you try with another browser maybe?/You're maybe trying another browser? Let's find out!"

**Comment by fkooman** [comment]
As a normal user you won't see this. Only users that have fiddled with their browser ("privacy") settings will see this. And in that case, it just provides the amount of information needed to indicate the problem. To really implement "user friendly" error messages we'd need to start working with "error codes" and also make them translatable etc. Might be a bit much at the moment. 

Like I mentioned elsewhere, it is already a lot better than other SAML implementations that just show a generic 400 or 500 without any info and requires the admin to look through the server logs...
